import hashlib
import json
import math

from app.models.broll import BrollMediaType, BrollOrientation, BrollProvider
from app.schemas.broll import MediaCandidateResult, MediaSearchInput


class UnsupportedMediaProviderError(ValueError):
    """Raised when a search targets a provider other than the local adapter."""


class UnsupportedMediaLanguageError(ValueError):
    """Raised when the local adapter receives a non-English search."""


class UnusableMediaSearchInputError(ValueError):
    """Raised when deterministic candidates cannot be produced from an input."""


class LocalMediaProvider:
    """Produce deterministic, metadata-only B-roll candidates for development.

    All candidates are synthetic safe-search placeholders. Their URLs use the
    reserved ``.invalid`` domain and are not expected to resolve or download.
    """

    _DEFAULT_DIMENSIONS: dict[BrollOrientation, tuple[int, int]] = {
        BrollOrientation.PORTRAIT: (1080, 1920),
        BrollOrientation.LANDSCAPE: (1920, 1080),
        BrollOrientation.SQUARE: (1080, 1080),
        BrollOrientation.UNKNOWN: (1280, 720),
    }

    async def search(self, search_input: MediaSearchInput) -> list[MediaCandidateResult]:
        query = self._validate_input(search_input)
        width, height = self._dimensions(search_input)
        query_hash = hashlib.sha256(query.casefold().encode("utf-8")).hexdigest()
        title = self._truncate_words(query, 8)
        candidates: list[MediaCandidateResult] = []

        for index in range(search_input.max_results):
            identity = self._candidate_identity(search_input, query, index)
            candidates.append(
                MediaCandidateResult(
                    provider=BrollProvider.LOCAL,
                    external_id=f"local-{identity[:20]}",
                    media_type=search_input.media_type,
                    title=f"{title} — option {index + 1}",
                    description=(
                        f"Synthetic {search_input.media_type.value} placeholder for {title}."
                    ),
                    source_url=f"https://local.invalid/source/{identity}",
                    preview_url=f"https://local.invalid/preview/{identity}",
                    download_url=f"https://local.invalid/download/{identity}",
                    width=width,
                    height=height,
                    duration_seconds=self._duration(search_input, identity),
                    mime_type=(
                        "video/mp4"
                        if search_input.media_type == BrollMediaType.VIDEO
                        else "image/jpeg"
                    ),
                    attribution="Synthetic metadata generated by ClipForge",
                    license_name="Development placeholder — no media asset",
                    photographer_or_creator="ClipForge LocalMediaProvider",
                    orientation=search_input.orientation,
                    relevance_score=round(max(0.0, 1.0 - index * 0.07), 2),
                    metadata_data={
                        "synthetic": True,
                        "safe_placeholder": True,
                        "query_hash": query_hash,
                        "candidate_index": index,
                    },
                )
            )
        return candidates

    @staticmethod
    def _validate_input(search_input: MediaSearchInput) -> str:
        if search_input.provider != BrollProvider.LOCAL:
            raise UnsupportedMediaProviderError(
                f"LocalMediaProvider cannot handle provider {search_input.provider.value}"
            )
        if search_input.language.split("-", maxsplit=1)[0].casefold() != "en":
            raise UnsupportedMediaLanguageError(
                f"LocalMediaProvider supports English only, not {search_input.language}"
            )
        query = " ".join(search_input.query.split())
        if not query or not any(character.isalnum() for character in query):
            raise UnusableMediaSearchInputError("media search query contains no meaningful text")
        if search_input.max_results < 1:
            raise UnusableMediaSearchInputError("max_results must be positive")
        if (
            search_input.min_duration_seconds < 0
            or search_input.max_duration_seconds < search_input.min_duration_seconds
        ):
            raise UnusableMediaSearchInputError("media duration range is invalid")
        if (
            search_input.media_type == BrollMediaType.VIDEO
            and search_input.max_duration_seconds <= 0
        ):
            raise UnusableMediaSearchInputError("video duration range has no positive value")
        return query

    @classmethod
    def _dimensions(cls, search_input: MediaSearchInput) -> tuple[int, int]:
        width, height = cls._DEFAULT_DIMENSIONS[search_input.orientation]
        width_scale = (search_input.min_width or 0) / width
        height_scale = (search_input.min_height or 0) / height
        scale = max(1.0, width_scale, height_scale)
        return math.ceil(width * scale), math.ceil(height * scale)

    @staticmethod
    def _duration(search_input: MediaSearchInput, identity: str) -> float | None:
        if search_input.media_type == BrollMediaType.IMAGE:
            return None
        minimum = max(search_input.min_duration_seconds, 0.1)
        maximum = search_input.max_duration_seconds
        if maximum < minimum:
            raise UnusableMediaSearchInputError("video duration range has no positive value")
        fraction = int(identity[:8], 16) / 0xFFFFFFFF
        return round(minimum + (maximum - minimum) * fraction, 3)

    @staticmethod
    def _candidate_identity(
        search_input: MediaSearchInput, query: str, candidate_index: int
    ) -> str:
        identity_data = {
            "candidate_index": candidate_index,
            "media_type": search_input.media_type.value,
            "orientation": search_input.orientation.value,
            "query": query,
            "section_order": search_input.section_order,
        }
        encoded = json.dumps(identity_data, sort_keys=True, ensure_ascii=False).encode()
        return hashlib.sha256(encoded).hexdigest()

    @staticmethod
    def _truncate_words(value: str, limit: int) -> str:
        return " ".join(value.split()[:limit])
